// exports.AUTH_TOKEN_KEY = "GITLABCODE_PEROSONAL_AUTH_TOKEN";
// exports.GITLAB_INSTANCE_KEY = "GITLABCODE_GITLAB_INSTANCE_KEY";
export const AUTH_TOKEN_KEY = "GITLABCODE_PEROSONAL_AUTH_TOKEN";
export const GITLAB_INSTANCE_KEY = "GITLABCODE_GITLAB_INSTANCE_KEY";
// export { AUTH_TOKEN_KEY, GITLAB_INSTANCE_KEY }